root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  payloads/flux-lidar/mapping-workflow-with-flux/installation-on-astro: payloads/flux-lidar/mapping-workflow-with-flux/setup.md
  payloads/flux-lidar/mapping-workflow-with-flux/processing-lidar-data-on-an-ipad: payloads/flux-lidar/mapping-workflow-with-flux/processing-scans.md
  payloads/flux-lidar/flux-software: payloads/flux-lidar/maintenance/flux-software.md
  payloads/flux-lidar/safety-information-and-technical-specifications: payloads/flux-lidar/technical-specs.md
